#*****************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# build_project.tcl: Tcl script for re-creating project 'ccpu'
#
# Generated by Vivado on Sun Sep 27 22:04:06 -0400 2026
# IP Build 6138677 on Thu May 22 03:10:11 MDT 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/../desktop build/ccpu.srcs/utils_1/imports/synth_1/board_top_wrapper.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/../src/program_counter.vhd"]"\
 "[file normalize "$origin_dir/../src/pc_plus_4.vhd"]"\
 "[file normalize "$origin_dir/../src/instruction_memory.vhd"]"\
 "[file normalize "$origin_dir/../src/control_unit.vhd"]"\
 "[file normalize "$origin_dir/../src/register_file.vhd"]"\
 "[file normalize "$origin_dir/../src/alu.vhd"]"\
 "[file normalize "$origin_dir/../src/data_memory.vhd"]"\
 "[file normalize "$origin_dir/../src/alu_a_mux.vhd"]"\
 "[file normalize "$origin_dir/../src/alu_b_mux.vhd"]"\
 "[file normalize "$origin_dir/../src/branch_adder.vhd"]"\
 "[file normalize "$origin_dir/../src/pc_src_mux.vhd"]"\
 "[file normalize "$origin_dir/../src/sign_extender.vhd"]"\
 "[file normalize "$origin_dir/../src/writeback_mux.vhd"]"\
 "[file normalize "$origin_dir/../src/load_extender.vhd"]"\
 "[file normalize "$origin_dir/../bd/top/hdl/top_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../src/board/single_step_clock.vhd"]"\
 "[file normalize "$origin_dir/../src/board/led_select_mux.vhd"]"\
 "[file normalize "$origin_dir/../src/board/seven_seg_controller.vhd"]"\
 "[file normalize "$origin_dir/../src/board/hex_to_7seg.vhd"]"\
 "[file normalize "$origin_dir/../bd/board_top/hdl/board_top_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../constraints/basys3.xdc"]"\
 "[file normalize "$origin_dir/../sim/top_wrapper_tb.vhd"]"\
 "[file normalize "$origin_dir/../sim/load_extender_tb.vhd"]"\
 "[file normalize "$origin_dir/../sim/control_unit_tb.vhd"]"\
 "[file normalize "$origin_dir/../sim/data_memory_tb.vhd"]"\
 "[file normalize "$origin_dir/../sim/instruction_memory_tb.vhd"]"\
 "[file normalize "$origin_dir/../sim/sign_extender_tb.vhd"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "ccpu"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "build_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../desktop build"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a35tcpg236-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a35tcpg236-1" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "VHDL" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "4" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "4" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "4" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "4" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "4" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "10" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../src/program_counter.vhd"] \
 [file normalize "${origin_dir}/../src/pc_plus_4.vhd"] \
 [file normalize "${origin_dir}/../src/instruction_memory.vhd"] \
 [file normalize "${origin_dir}/../src/control_unit.vhd"] \
 [file normalize "${origin_dir}/../src/register_file.vhd"] \
 [file normalize "${origin_dir}/../src/alu.vhd"] \
 [file normalize "${origin_dir}/../src/data_memory.vhd"] \
 [file normalize "${origin_dir}/../src/alu_a_mux.vhd"] \
 [file normalize "${origin_dir}/../src/alu_b_mux.vhd"] \
 [file normalize "${origin_dir}/../src/branch_adder.vhd"] \
 [file normalize "${origin_dir}/../src/pc_src_mux.vhd"] \
 [file normalize "${origin_dir}/../src/sign_extender.vhd"] \
 [file normalize "${origin_dir}/../src/writeback_mux.vhd"] \
 [file normalize "${origin_dir}/../src/load_extender.vhd"] \
 [file normalize "${origin_dir}/../bd/top/hdl/top_wrapper.vhd"] \
 [file normalize "${origin_dir}/../src/board/single_step_clock.vhd"] \
 [file normalize "${origin_dir}/../src/board/led_select_mux.vhd"] \
 [file normalize "${origin_dir}/../src/board/seven_seg_controller.vhd"] \
 [file normalize "${origin_dir}/../src/board/hex_to_7seg.vhd"] \
 [file normalize "${origin_dir}/../bd/board_top/hdl/board_top_wrapper.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../src/program_counter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/pc_plus_4.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/instruction_memory.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/control_unit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/register_file.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/alu.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/data_memory.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/alu_a_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/alu_b_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/branch_adder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/pc_src_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/sign_extender.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/writeback_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/load_extender.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../bd/top/hdl/top_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/board/single_step_clock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/board/led_select_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/board/seven_seg_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/board/hex_to_7seg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../bd/board_top/hdl/board_top_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "board_top_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constraints/basys3.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../constraints/basys3.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7a35tcpg236-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/../sim/top_wrapper_tb.vhd"] \
 [file normalize "${origin_dir}/../sim/load_extender_tb.vhd"] \
 [file normalize "${origin_dir}/../sim/control_unit_tb.vhd"] \
 [file normalize "${origin_dir}/../sim/data_memory_tb.vhd"] \
 [file normalize "${origin_dir}/../sim/instruction_memory_tb.vhd"] \
 [file normalize "${origin_dir}/../sim/sign_extender_tb.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../sim/top_wrapper_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sim/load_extender_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "$origin_dir/../sim/control_unit_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "$origin_dir/../sim/data_memory_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "$origin_dir/../sim/instruction_memory_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "$origin_dir/../sim/sign_extender_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "top_wrapper_tb" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj


# Adding sources referenced in BDs, if not already added
if { [get_files [list program_counter.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/program_counter.vhd
}
if { [get_files [list pc_plus_4.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/pc_plus_4.vhd
}
if { [get_files [list instruction_memory.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/instruction_memory.vhd
}
if { [get_files [list control_unit.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/control_unit.vhd
}
if { [get_files [list register_file.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/register_file.vhd
}
if { [get_files [list alu.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/alu.vhd
}
if { [get_files [list data_memory.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/data_memory.vhd
}
if { [get_files [list alu_a_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/alu_a_mux.vhd
}
if { [get_files [list alu_b_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/alu_b_mux.vhd
}
if { [get_files [list branch_adder.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/branch_adder.vhd
}
if { [get_files [list pc_src_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/pc_src_mux.vhd
}
if { [get_files [list sign_extender.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/sign_extender.vhd
}
if { [get_files [list writeback_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/writeback_mux.vhd
}
if { [get_files [list load_extender.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/load_extender.vhd
}


# Proc to create BD top
proc cr_bd_top { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# program_counter, pc_plus_4, instruction_memory, control_unit, register_file, alu, data_memory, alu_a_mux, alu_b_mux, branch_adder, pc_src_mux, sign_extender, writeback_mux, load_extender



  # CHANGE DESIGN NAME HERE
  set design_name top

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:inline_hdl:ilslice:1.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  program_counter\
  pc_plus_4\
  instruction_memory\
  control_unit\
  register_file\
  alu\
  data_memory\
  alu_a_mux\
  alu_b_mux\
  branch_adder\
  pc_src_mux\
  sign_extender\
  writeback_mux\
  load_extender\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set clk_0 [ create_bd_port -dir I -type clk clk_0 ]
  set reset_0 [ create_bd_port -dir I -type rst reset_0 ]
  set writebackOUT [ create_bd_port -dir O -from 31 -to 0 -type data writebackOUT ]

  # Create instance: program_counter_0, and set properties
  set block_name program_counter
  set block_cell_name program_counter_0
  if { [catch {set program_counter_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $program_counter_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: pc_plus_4_0, and set properties
  set block_name pc_plus_4
  set block_cell_name pc_plus_4_0
  if { [catch {set pc_plus_4_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $pc_plus_4_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: instruction_memory_0, and set properties
  set block_name instruction_memory
  set block_cell_name instruction_memory_0
  if { [catch {set instruction_memory_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $instruction_memory_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: control_unit_0, and set properties
  set block_name control_unit
  set block_cell_name control_unit_0
  if { [catch {set control_unit_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $control_unit_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: register_file_0, and set properties
  set block_name register_file
  set block_cell_name register_file_0
  if { [catch {set register_file_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $register_file_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: alu_0, and set properties
  set block_name alu
  set block_cell_name alu_0
  if { [catch {set alu_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $alu_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: data_memory_0, and set properties
  set block_name data_memory
  set block_cell_name data_memory_0
  if { [catch {set data_memory_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $data_memory_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: alu_a_mux_0, and set properties
  set block_name alu_a_mux
  set block_cell_name alu_a_mux_0
  if { [catch {set alu_a_mux_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $alu_a_mux_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: alu_b_mux_0, and set properties
  set block_name alu_b_mux
  set block_cell_name alu_b_mux_0
  if { [catch {set alu_b_mux_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $alu_b_mux_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: branch_adder_0, and set properties
  set block_name branch_adder
  set block_cell_name branch_adder_0
  if { [catch {set branch_adder_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $branch_adder_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: pc_src_mux_0, and set properties
  set block_name pc_src_mux
  set block_cell_name pc_src_mux_0
  if { [catch {set pc_src_mux_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $pc_src_mux_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: sign_extender_0, and set properties
  set block_name sign_extender
  set block_cell_name sign_extender_0
  if { [catch {set sign_extender_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $sign_extender_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: writeback_mux_0, and set properties
  set block_name writeback_mux
  set block_cell_name writeback_mux_0
  if { [catch {set writeback_mux_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $writeback_mux_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: load_extender_0, and set properties
  set block_name load_extender
  set block_cell_name load_extender_0
  if { [catch {set load_extender_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $load_extender_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: ilslice_0, and set properties
  set ilslice_0 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilslice:1.0 ilslice_0 ]
  set_property -dict [list \
    CONFIG.DIN_FROM {19} \
    CONFIG.DIN_TO {15} \
    CONFIG.DIN_WIDTH {32} \
  ] $ilslice_0


  # Create instance: ilslice_1, and set properties
  set ilslice_1 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilslice:1.0 ilslice_1 ]
  set_property -dict [list \
    CONFIG.DIN_FROM {24} \
    CONFIG.DIN_TO {20} \
  ] $ilslice_1


  # Create instance: ilslice_2, and set properties
  set ilslice_2 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilslice:1.0 ilslice_2 ]
  set_property -dict [list \
    CONFIG.DIN_FROM {11} \
    CONFIG.DIN_TO {7} \
  ] $ilslice_2


  # Create port connections
  connect_bd_net -net alu_0_result  [get_bd_pins alu_0/result] \
  [get_bd_pins data_memory_0/address] \
  [get_bd_pins pc_src_mux_0/jalr] \
  [get_bd_pins writeback_mux_0/alu]
  connect_bd_net -net alu_0_zero  [get_bd_pins alu_0/zero] \
  [get_bd_pins control_unit_0/alu_zero]
  connect_bd_net -net alu_a_mux_0_alu_a  [get_bd_pins alu_a_mux_0/alu_a] \
  [get_bd_pins alu_0/a]
  connect_bd_net -net alu_b_mux_0_alu_b  [get_bd_pins alu_b_mux_0/alu_b] \
  [get_bd_pins alu_0/b]
  connect_bd_net -net branch_adder_0_target  [get_bd_pins branch_adder_0/target] \
  [get_bd_pins pc_src_mux_0/branch]
  connect_bd_net -net clk_0_1  [get_bd_ports clk_0] \
  [get_bd_pins data_memory_0/clk] \
  [get_bd_pins program_counter_0/clk] \
  [get_bd_pins register_file_0/clk]
  connect_bd_net -net control_unit_0_alu_a_sel  [get_bd_pins control_unit_0/alu_a_sel] \
  [get_bd_pins alu_a_mux_0/alu_a_sel]
  connect_bd_net -net control_unit_0_alu_b_sel  [get_bd_pins control_unit_0/alu_b_sel] \
  [get_bd_pins alu_b_mux_0/alu_b_sel]
  connect_bd_net -net control_unit_0_alu_op  [get_bd_pins control_unit_0/alu_op] \
  [get_bd_pins alu_0/alu_op]
  connect_bd_net -net control_unit_0_load_unsigned  [get_bd_pins control_unit_0/load_unsigned] \
  [get_bd_pins load_extender_0/load_unsigned]
  connect_bd_net -net control_unit_0_mem_size  [get_bd_pins control_unit_0/mem_size] \
  [get_bd_pins data_memory_0/mem_size] \
  [get_bd_pins load_extender_0/mem_size]
  connect_bd_net -net control_unit_0_mem_write  [get_bd_pins control_unit_0/mem_write] \
  [get_bd_pins data_memory_0/write_enable]
  connect_bd_net -net control_unit_0_pc_src_sel  [get_bd_pins control_unit_0/pc_src_sel] \
  [get_bd_pins pc_src_mux_0/pc_src_sel]
  connect_bd_net -net control_unit_0_reg_write  [get_bd_pins control_unit_0/reg_write] \
  [get_bd_pins register_file_0/write_enable]
  connect_bd_net -net control_unit_0_wb_sel  [get_bd_pins control_unit_0/wb_sel] \
  [get_bd_pins writeback_mux_0/wb_sel]
  connect_bd_net -net data_memory_0_data  [get_bd_pins data_memory_0/data] \
  [get_bd_pins load_extender_0/raw_data]
  connect_bd_net -net ilslice_0_Dout  [get_bd_pins ilslice_0/Dout] \
  [get_bd_pins register_file_0/read_addr1]
  connect_bd_net -net ilslice_1_Dout  [get_bd_pins ilslice_1/Dout] \
  [get_bd_pins register_file_0/read_addr2]
  connect_bd_net -net ilslice_2_Dout  [get_bd_pins ilslice_2/Dout] \
  [get_bd_pins register_file_0/write_addr]
  connect_bd_net -net instruction_memory_0_instruction  [get_bd_pins instruction_memory_0/instruction] \
  [get_bd_pins ilslice_0/Din] \
  [get_bd_pins ilslice_1/Din] \
  [get_bd_pins ilslice_2/Din] \
  [get_bd_pins control_unit_0/instruction] \
  [get_bd_pins sign_extender_0/instruction]
  connect_bd_net -net load_extender_0_extended  [get_bd_pins load_extender_0/extended] \
  [get_bd_pins writeback_mux_0/data]
  connect_bd_net -net pc_plus_4_0_pc_out  [get_bd_pins pc_plus_4_0/pc_out] \
  [get_bd_pins pc_src_mux_0/pc4] \
  [get_bd_pins writeback_mux_0/pc4]
  connect_bd_net -net pc_src_mux_0_pc_src  [get_bd_pins pc_src_mux_0/pc_src] \
  [get_bd_pins program_counter_0/next_addr]
  connect_bd_net -net program_counter_0_curr_addr  [get_bd_pins program_counter_0/curr_addr] \
  [get_bd_pins alu_a_mux_0/pc] \
  [get_bd_pins branch_adder_0/pc] \
  [get_bd_pins instruction_memory_0/address] \
  [get_bd_pins pc_plus_4_0/pc_in]
  connect_bd_net -net register_file_0_data1  [get_bd_pins register_file_0/data1] \
  [get_bd_pins alu_a_mux_0/data1]
  connect_bd_net -net register_file_0_data2  [get_bd_pins register_file_0/data2] \
  [get_bd_pins alu_b_mux_0/data2] \
  [get_bd_pins data_memory_0/write_data]
  connect_bd_net -net reset_0_1  [get_bd_ports reset_0] \
  [get_bd_pins program_counter_0/reset] \
  [get_bd_pins register_file_0/reset]
  connect_bd_net -net sign_extender_0_extended  [get_bd_pins sign_extender_0/extended] \
  [get_bd_pins alu_b_mux_0/immediate] \
  [get_bd_pins branch_adder_0/immediate]
  connect_bd_net -net writeback_mux_0_writeback  [get_bd_pins writeback_mux_0/writeback] \
  [get_bd_ports writebackOUT] \
  [get_bd_pins register_file_0/write_data]

  # Create address segments

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.708942",
   "Default View_TopLeft":"-103,49",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0
#  -string -flagsOSRD
preplace port port-id_clk_0 -pg 1 -lvl 0 -x -390 -y 120 -defaultsOSRD
preplace port port-id_reset_0 -pg 1 -lvl 0 -x -390 -y 170 -defaultsOSRD
preplace portBus writebackOUT -pg 1 -lvl 10 -x 2850 -y -50 -defaultsOSRD
preplace inst program_counter_0 -pg 1 -lvl 1 -x -80 -y 170 -defaultsOSRD -resize 165 176
preplace inst pc_plus_4_0 -pg 1 -lvl 2 -x 230 -y -380 -defaultsOSRD
preplace inst instruction_memory_0 -pg 1 -lvl 2 -x 230 -y 170 -defaultsOSRD -resize 272 346
preplace inst control_unit_0 -pg 1 -lvl 3 -x 580 -y -180 -defaultsOSRD
preplace inst register_file_0 -pg 1 -lvl 4 -x 1000 -y 310 -defaultsOSRD -resize 360 658
preplace inst alu_0 -pg 1 -lvl 6 -x 1700 -y 370 -defaultsOSRD
preplace inst data_memory_0 -pg 1 -lvl 7 -x 2050 -y 360 -defaultsOSRD -resize 237 464
preplace inst alu_a_mux_0 -pg 1 -lvl 5 -x 1380 -y 90 -defaultsOSRD
preplace inst alu_b_mux_0 -pg 1 -lvl 5 -x 1380 -y 570 -defaultsOSRD
preplace inst branch_adder_0 -pg 1 -lvl 6 -x 1700 -y -370 -defaultsOSRD
preplace inst pc_src_mux_0 -pg 1 -lvl 7 -x 2050 -y -360 -defaultsOSRD
preplace inst sign_extender_0 -pg 1 -lvl 4 -x 1000 -y 700 -defaultsOSRD
preplace inst writeback_mux_0 -pg 1 -lvl 9 -x 2680 -y 390 -defaultsOSRD
preplace inst load_extender_0 -pg 1 -lvl 8 -x 2360 -y 380 -defaultsOSRD
preplace inst ilslice_0 -pg 1 -lvl 3 -x 580 -y 110 -defaultsOSRD
preplace inst ilslice_1 -pg 1 -lvl 3 -x 580 -y 210 -defaultsOSRD
preplace inst ilslice_2 -pg 1 -lvl 3 -x 580 -y 310 -defaultsOSRD
preplace netloc alu_0_result 1 6 3 1900 100 N 100 2520
preplace netloc alu_0_zero 1 2 5 430 -40 750J -60 NJ -60 NJ -60 1840
preplace netloc alu_a_mux_0_alu_a 1 5 1 1520 90n
preplace netloc alu_b_mux_0_alu_b 1 5 1 1540 370n
preplace netloc branch_adder_0_target 1 6 1 N -370
preplace netloc clk_0_1 1 0 7 -200 -50 N -50 400 -10 790 -110 N -110 N -110 1880
preplace netloc control_unit_0_alu_a_sel 1 3 2 NJ -200 1230
preplace netloc control_unit_0_alu_b_sel 1 3 2 NJ -180 1200
preplace netloc control_unit_0_alu_op 1 3 3 NJ -220 NJ -220 1530
preplace netloc control_unit_0_load_unsigned 1 3 5 NJ -100 NJ -100 NJ -100 NJ -100 2200
preplace netloc control_unit_0_mem_size 1 3 5 NJ -120 NJ -120 NJ -120 1870J 110 2190
preplace netloc control_unit_0_mem_write 1 3 4 NJ -240 NJ -240 NJ -240 1890
preplace netloc control_unit_0_pc_src_sel 1 3 4 730 -300 NJ -300 NJ -300 1910J
preplace netloc control_unit_0_reg_write 1 3 1 740 -260n
preplace netloc control_unit_0_wb_sel 1 3 6 NJ -160 NJ -160 NJ -160 NJ -160 NJ -160 2510
preplace netloc data_memory_0_data 1 7 1 N 360
preplace netloc ilslice_0_Dout 1 3 1 N 110
preplace netloc ilslice_1_Dout 1 3 1 N 210
preplace netloc ilslice_2_Dout 1 3 1 N 310
preplace netloc instruction_memory_0_instruction 1 2 2 420 590 730
preplace netloc load_extender_0_extended 1 8 1 N 380
preplace netloc pc_plus_4_0_pc_out 1 2 7 NJ -380 NJ -380 N -380 1530 -440 1910 -450 N -450 2530
preplace netloc pc_src_mux_0_pc_src 1 0 8 -190 -40 NJ -40 390J -20 760J -70 NJ -70 NJ -70 NJ -70 2190
preplace netloc program_counter_0_curr_addr 1 1 5 70 -30 N -30 770 -50 1240 -50 1540
preplace netloc register_file_0_data1 1 4 1 N 70
preplace netloc register_file_0_data2 1 4 3 1240 460 N 460 N
preplace netloc reset_0_1 1 0 4 -200 600 N 600 N 600 N
preplace netloc sign_extender_0_extended 1 4 2 1220 -360 N
preplace netloc writeback_mux_0_writeback 1 3 7 800 -40 NJ -40 NJ -40 NJ -40 NJ -40 NJ -40 2820
levelinfo -pg 1 -390 -80 230 580 1000 1380 1700 2050 2360 2680 2850
pagesize -pg 1 -db -bbox -sgen -490 -620 3030 760
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  save_bd_design
common::send_gid_msg -ssname BD::TCL -id 2050 -severity "WARNING" "This Tcl script was generated from a block design that has not been validated. It is possible that design <$design_name> may result in errors during validation."

  close_bd_design $design_name 
}
# End of cr_bd_top()

cr_bd_top ""
set_property REGISTERED_WITH_MANAGER "1" [get_files top.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files top.bd ] 

if { [get_files [list program_counter.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/program_counter.vhd
}
if { [get_files [list pc_plus_4.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/pc_plus_4.vhd
}
if { [get_files [list instruction_memory.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/instruction_memory.vhd
}
if { [get_files [list control_unit.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/control_unit.vhd
}
if { [get_files [list register_file.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/register_file.vhd
}
if { [get_files [list alu.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/alu.vhd
}
if { [get_files [list data_memory.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/data_memory.vhd
}
if { [get_files [list alu_a_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/alu_a_mux.vhd
}
if { [get_files [list alu_b_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/alu_b_mux.vhd
}
if { [get_files [list branch_adder.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/branch_adder.vhd
}
if { [get_files [list pc_src_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/pc_src_mux.vhd
}
if { [get_files [list sign_extender.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/sign_extender.vhd
}
if { [get_files [list writeback_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/writeback_mux.vhd
}
if { [get_files [list load_extender.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/load_extender.vhd
}
if { [get_files [list top_wrapper.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../bd/top/hdl/top_wrapper.vhd
}
if { [get_files [list single_step_clock.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/board/single_step_clock.vhd
}
if { [get_files [list led_select_mux.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/board/led_select_mux.vhd
}
if { [get_files [list seven_seg_controller.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/board/seven_seg_controller.vhd
}
if { [get_files [list hex_to_7seg.vhd]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../src/board/hex_to_7seg.vhd
}


# Proc to create BD board_top
proc cr_bd_board_top { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# top_wrapper, single_step_clock, led_select_mux, seven_seg_controller, hex_to_7seg



  # CHANGE DESIGN NAME HERE
  set design_name board_top

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:inline_hdl:ilconstant:1.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  top_wrapper\
  single_step_clock\
  led_select_mux\
  seven_seg_controller\
  hex_to_7seg\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set board_clk [ create_bd_port -dir I board_clk ]
  set btn_step [ create_bd_port -dir I btn_step ]
  set reset [ create_bd_port -dir I reset ]
  set led_sel [ create_bd_port -dir I led_sel ]
  set dp [ create_bd_port -dir O -from 0 -to 0 dp ]
  set seg [ create_bd_port -dir O -from 6 -to 0 seg ]
  set an [ create_bd_port -dir O -from 3 -to 0 an ]

  # Create instance: top_wrapper_0, and set properties
  set block_name top_wrapper
  set block_cell_name top_wrapper_0
  if { [catch {set top_wrapper_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $top_wrapper_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: single_step_clock_0, and set properties
  set block_name single_step_clock
  set block_cell_name single_step_clock_0
  if { [catch {set single_step_clock_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $single_step_clock_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: led_select_mux_0, and set properties
  set block_name led_select_mux
  set block_cell_name led_select_mux_0
  if { [catch {set led_select_mux_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $led_select_mux_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: seven_seg_controller_0, and set properties
  set block_name seven_seg_controller
  set block_cell_name seven_seg_controller_0
  if { [catch {set seven_seg_controller_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $seven_seg_controller_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: hex_to_7seg_0, and set properties
  set block_name hex_to_7seg
  set block_cell_name hex_to_7seg_0
  if { [catch {set hex_to_7seg_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $hex_to_7seg_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: dp, and set properties
  set dp [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconstant:1.0 dp ]

  # Create port connections
  connect_bd_net -net board_clk_1  [get_bd_ports board_clk] \
  [get_bd_pins seven_seg_controller_0/clk] \
  [get_bd_pins single_step_clock_0/clk]
  connect_bd_net -net btn_step_1  [get_bd_ports btn_step] \
  [get_bd_pins single_step_clock_0/btn_in]
  connect_bd_net -net dp_dout  [get_bd_pins dp/dout] \
  [get_bd_ports dp]
  connect_bd_net -net hex_to_7seg_0_seg  [get_bd_pins hex_to_7seg_0/seg] \
  [get_bd_ports seg]
  connect_bd_net -net led_sel_1  [get_bd_ports led_sel] \
  [get_bd_pins led_select_mux_0/led_sel]
  connect_bd_net -net led_select_mux_0_led  [get_bd_pins led_select_mux_0/led] \
  [get_bd_pins seven_seg_controller_0/value]
  connect_bd_net -net reset_1  [get_bd_ports reset] \
  [get_bd_pins top_wrapper_0/reset_0]
  connect_bd_net -net seven_seg_controller_0_an  [get_bd_pins seven_seg_controller_0/an] \
  [get_bd_ports an]
  connect_bd_net -net seven_seg_controller_0_hex_digit  [get_bd_pins seven_seg_controller_0/hex_digit] \
  [get_bd_pins hex_to_7seg_0/hex_digit]
  connect_bd_net -net single_step_clock_0_step_pulse  [get_bd_pins single_step_clock_0/step_pulse] \
  [get_bd_pins top_wrapper_0/clk_0]
  connect_bd_net -net top_wrapper_0_writebackOUT  [get_bd_pins top_wrapper_0/writebackOUT] \
  [get_bd_pins led_select_mux_0/writeback]

  # Create address segments

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"1.0",
   "Default View_TopLeft":"-718,-629",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0
#  -string -flagsOSRD
preplace port port-id_board_clk -pg 1 -lvl 0 -x -560 -y -300 -defaultsOSRD
preplace port port-id_btn_step -pg 1 -lvl 0 -x -560 -y -220 -defaultsOSRD
preplace port port-id_reset -pg 1 -lvl 0 -x -560 -y -130 -defaultsOSRD
preplace port port-id_led_sel -pg 1 -lvl 0 -x -560 -y -110 -defaultsOSRD
preplace portBus dp -pg 1 -lvl 6 -x 1070 -y -80 -defaultsOSRD
preplace portBus seg -pg 1 -lvl 6 -x 1070 -y -230 -defaultsOSRD
preplace portBus an -pg 1 -lvl 6 -x 1070 -y -290 -defaultsOSRD
preplace inst top_wrapper_0 -pg 1 -lvl 2 -x 90 -y -220 -defaultsOSRD
preplace inst single_step_clock_0 -pg 1 -lvl 1 -x -170 -y -230 -defaultsOSRD
preplace inst led_select_mux_0 -pg 1 -lvl 3 -x 370 -y -210 -defaultsOSRD
preplace inst seven_seg_controller_0 -pg 1 -lvl 4 -x 650 -y -220 -defaultsOSRD
preplace inst hex_to_7seg_0 -pg 1 -lvl 5 -x 920 -y -230 -defaultsOSRD
preplace inst dp -pg 1 -lvl 5 -x 920 -y -80 -defaultsOSRD
preplace netloc board_clk_1 1 0 4 -290 -310 N -310 N -310 500
preplace netloc btn_step_1 1 0 1 N -220
preplace netloc dp_dout 1 5 1 N -80
preplace netloc hex_to_7seg_0_seg 1 5 1 N -230
preplace netloc led_sel_1 1 0 3 -540J -320 N -320 230
preplace netloc led_select_mux_0_led 1 3 1 N -210
preplace netloc reset_1 1 0 2 -280J -300 -60
preplace netloc seven_seg_controller_0_an 1 4 2 780 -290 NJ
preplace netloc seven_seg_controller_0_hex_digit 1 4 1 N -230
preplace netloc single_step_clock_0_step_pulse 1 1 1 N -230
preplace netloc top_wrapper_0_writebackOUT 1 2 1 NJ -220
levelinfo -pg 1 -560 -170 90 370 650 920 1070
pagesize -pg 1 -db -bbox -sgen -680 -520 1180 140
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  save_bd_design
common::send_gid_msg -ssname BD::TCL -id 2050 -severity "WARNING" "This Tcl script was generated from a block design that has not been validated. It is possible that design <$design_name> may result in errors during validation."

  close_bd_design $design_name 
}
# End of cr_bd_board_top()

cr_bd_board_top ""
set_property REGISTERED_WITH_MANAGER "1" [get_files board_top.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files board_top.bd ] 

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a35tcpg236-1 -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a35tcpg236-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a35tcpg236-1 -flow {Vivado Implementation 2025} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a35tcpg236-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
