# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/board_top/ip/board_top_top_wrapper_0_0/board_top_top_wrapper_0_0.xci
# IP: The module: 'board_top_top_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: E:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_program_counter_0_0/top_program_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_program_counter_0_0 || ORIG_REF_NAME==top_program_counter_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_pc_plus_4_0_0/top_pc_plus_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_pc_plus_4_0_0 || ORIG_REF_NAME==top_pc_plus_4_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_instruction_memory_0_0/top_instruction_memory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_instruction_memory_0_0 || ORIG_REF_NAME==top_instruction_memory_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_control_unit_0_0/top_control_unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_control_unit_0_0 || ORIG_REF_NAME==top_control_unit_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_register_file_0_0/top_register_file_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_register_file_0_0 || ORIG_REF_NAME==top_register_file_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_alu_0_0/top_alu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alu_0_0 || ORIG_REF_NAME==top_alu_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_data_memory_0_0/top_data_memory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_data_memory_0_0 || ORIG_REF_NAME==top_data_memory_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_alu_a_mux_0_0/top_alu_a_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alu_a_mux_0_0 || ORIG_REF_NAME==top_alu_a_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_alu_b_mux_0_0/top_alu_b_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alu_b_mux_0_0 || ORIG_REF_NAME==top_alu_b_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_branch_adder_0_0/top_branch_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_branch_adder_0_0 || ORIG_REF_NAME==top_branch_adder_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_pc_src_mux_0_0/top_pc_src_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_pc_src_mux_0_0 || ORIG_REF_NAME==top_pc_src_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_sign_extender_0_0/top_sign_extender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_sign_extender_0_0 || ORIG_REF_NAME==top_sign_extender_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_writeback_mux_0_0/top_writeback_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_writeback_mux_0_0 || ORIG_REF_NAME==top_writeback_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_load_extender_0_0/top_load_extender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_load_extender_0_0 || ORIG_REF_NAME==top_load_extender_0_0} -quiet] -quiet

# XDC: E:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/top_ooc.xdc

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/board_top/ip/board_top_top_wrapper_0_0/board_top_top_wrapper_0_0.xci
# IP: The module: 'board_top_top_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: E:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/top.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_program_counter_0_0/top_program_counter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_program_counter_0_0 || ORIG_REF_NAME==top_program_counter_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_pc_plus_4_0_0/top_pc_plus_4_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_pc_plus_4_0_0 || ORIG_REF_NAME==top_pc_plus_4_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_instruction_memory_0_0/top_instruction_memory_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_instruction_memory_0_0 || ORIG_REF_NAME==top_instruction_memory_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_control_unit_0_0/top_control_unit_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_control_unit_0_0 || ORIG_REF_NAME==top_control_unit_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_register_file_0_0/top_register_file_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_register_file_0_0 || ORIG_REF_NAME==top_register_file_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_alu_0_0/top_alu_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alu_0_0 || ORIG_REF_NAME==top_alu_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_data_memory_0_0/top_data_memory_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_data_memory_0_0 || ORIG_REF_NAME==top_data_memory_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_alu_a_mux_0_0/top_alu_a_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alu_a_mux_0_0 || ORIG_REF_NAME==top_alu_a_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_alu_b_mux_0_0/top_alu_b_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_alu_b_mux_0_0 || ORIG_REF_NAME==top_alu_b_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_branch_adder_0_0/top_branch_adder_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_branch_adder_0_0 || ORIG_REF_NAME==top_branch_adder_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_pc_src_mux_0_0/top_pc_src_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_pc_src_mux_0_0 || ORIG_REF_NAME==top_pc_src_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_sign_extender_0_0/top_sign_extender_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_sign_extender_0_0 || ORIG_REF_NAME==top_sign_extender_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_writeback_mux_0_0/top_writeback_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_writeback_mux_0_0 || ORIG_REF_NAME==top_writeback_mux_0_0} -quiet] -quiet

# IP: e:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/ip/top_load_extender_0_0/top_load_extender_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_load_extender_0_0 || ORIG_REF_NAME==top_load_extender_0_0} -quiet] -quiet

# XDC: E:/Programming/Personal/Custom CPU/customcpu/v1-single-cycle/bd/top/top_ooc.xdc
